### ISSUE TITLE
小米手机相册备份软件闪退

### ISSUE THREAD

**Issue by hangyubin** [linkease/doc.linkease.com#29]
小米手机相册备份软件闪退
手上的APP报错日志：
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:566)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	... 1 more
Caused by: go.Universe$proxyerror: target device not found
	at easysdk.EasySDK.startBackup(Native Method)
	at com.jiajia.cloud.ui.linkease.fragment.PhotoFsFragment.x(Unknown Source:69)
	at com.jiajia.cloud.ui.linkease.fragment.PhotoFsFragment.a(Unknown Source:0)
	at com.jiajia.cloud.ui.linkease.fragment.PhotoFsFragment$s.a(Unknown Source:41)
	at com.jiajia.cloud.ui.linkease.fragment.PhotoFsFragment$s.invoke(Unknown Source:2)
	at com.jiajia.cloud.utils.ext.d$a.onClick(Unknown Source:37)
	at android.view.View.performClick(View.java:7750)
	at android.view.View.performC

**Comment by jannson** [comment]
请更新新版本，还有问题可以来我们 VIP 群，跟开发人员确认下。谢谢。
